"""initial schema

Revision ID: 04043399b769
Revises: 
Create Date: 2026-08-31 07:15:13.354824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04043399b769'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dashboard_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('submitting_account', sa.String(length=255), nullable=True),
    sa.Column('from_addr', sa.String(length=320), nullable=False),
    sa.Column('rcpt_to', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('message_id_header', sa.String(length=512), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('spool_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_used', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_message_id_header'), ['message_id_header'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)
        batch_op.create_index('ix_messages_status_next_attempt', ['status', 'next_attempt_at'], unique=False)

    op.create_table('provider_overrides',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('provider_quota',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'period_key', 'scope')
    )
    op.create_table('provider_state',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('half_open_probes', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('send_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send_log', schema=None) as batch_op:
        batch_op.create_index('ix_send_log_provider_sent_at', ['provider', 'sent_at'], unique=False)

    op.create_table('delivery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('smtp_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_attempts_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_message_id'))

    op.drop_table('delivery_attempts')
    with op.batch_alter_table('send_log', schema=None) as batch_op:
        batch_op.drop_index('ix_send_log_provider_sent_at')

    op.drop_table('send_log')
    op.drop_table('provider_state')
    op.drop_table('provider_quota')
    op.drop_table('provider_overrides')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_status_next_attempt')
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_received_at'))
        batch_op.drop_index(batch_op.f('ix_messages_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_messages_message_id_header'))

    op.drop_table('messages')
    op.drop_table('dashboard_users')
    op.drop_table('accounts')
    # ### end Alembic commands ###
